package program.ahorcado;

import javax.swing.JOptionPane;

/**
 *
 * @author fran
 */
public class GuiAhorcado extends javax.swing.JFrame {

    private Ahorcado juego;
    private AhorcadoDibujo ahorcadoDibujo;

    // Constructor
    public GuiAhorcado() {
        juego = new Ahorcado();
        ahorcadoDibujo = new AhorcadoDibujo();
        initComponents();

        // Agregar el panel de dibujo al panelHorca
        panelHorca.setLayout(new java.awt.BorderLayout());
        panelHorca.add(ahorcadoDibujo, java.awt.BorderLayout.CENTER);

        setLocationRelativeTo(null);
        actualizarPantalla();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelHorca = new javax.swing.JPanel();
        panelLetrasUsadas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textField_LetrasUsadas = new javax.swing.JTextPane();
        jPanel4 = new javax.swing.JPanel();
        label_Intentos = new javax.swing.JLabel();
        labelPalabra = new javax.swing.JLabel();
        label_IntroducirLetra = new javax.swing.JLabel();
        textField_LetraIn = new javax.swing.JTextField();
        btnInLetra = new javax.swing.JButton();
        pistaLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(153, 153, 255));

        panelHorca.setBackground(new java.awt.Color(204, 204, 255));
        panelHorca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHorca.setForeground(new java.awt.Color(255, 204, 204));
        panelHorca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout panelHorcaLayout = new javax.swing.GroupLayout(panelHorca);
        panelHorca.setLayout(panelHorcaLayout);
        panelHorcaLayout.setHorizontalGroup(
            panelHorcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );
        panelHorcaLayout.setVerticalGroup(
            panelHorcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelLetrasUsadas.setBackground(new java.awt.Color(204, 204, 255));
        panelLetrasUsadas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Letras usadas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        panelLetrasUsadas.setForeground(new java.awt.Color(0, 0, 0));
        panelLetrasUsadas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        textField_LetrasUsadas.setEditable(false);
        jScrollPane1.setViewportView(textField_LetrasUsadas);

        javax.swing.GroupLayout panelLetrasUsadasLayout = new javax.swing.GroupLayout(panelLetrasUsadas);
        panelLetrasUsadas.setLayout(panelLetrasUsadasLayout);
        panelLetrasUsadasLayout.setHorizontalGroup(
            panelLetrasUsadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLetrasUsadasLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        panelLetrasUsadasLayout.setVerticalGroup(
            panelLetrasUsadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLetrasUsadasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label_Intentos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_Intentos.setForeground(new java.awt.Color(0, 0, 0));
        label_Intentos.setText("Intentos Restantes : ");

        labelPalabra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelPalabra.setForeground(new java.awt.Color(0, 0, 0));
        labelPalabra.setText(" ");

        label_IntroducirLetra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_IntroducirLetra.setForeground(new java.awt.Color(0, 0, 0));
        label_IntroducirLetra.setText("Introduce tu letra :");

        textField_LetraIn.setColumns(3);
        textField_LetraIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textField_LetraIn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_LetraIn.setAutoscrolls(false);
        textField_LetraIn.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnInLetra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInLetra.setText("Ok");
        btnInLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInLetraActionPerformed(evt);
            }
        });

        pistaLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pistaLabel.setForeground(new java.awt.Color(0, 0, 0));
        pistaLabel.setText("Pista : ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(label_IntroducirLetra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_LetraIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInLetra))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(labelPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pistaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_Intentos)
                .addGap(27, 27, 27))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Intentos)
                    .addComponent(pistaLabel))
                .addGap(57, 57, 57)
                .addComponent(labelPalabra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_IntroducirLetra)
                    .addComponent(textField_LetraIn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo.setText("El Ahorcado");
        labelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(labelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelTitulo)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                            .addComponent(panelHorca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelLetrasUsadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)))
                .addGap(38, 38, 38))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelHorca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelLetrasUsadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInLetraActionPerformed

        if (!(textField_LetraIn.getText().trim().isEmpty())) {
            char letra = Character.toUpperCase(textField_LetraIn.getText().charAt(0));
            textField_LetraIn.setText("");
            juego.procesarLetra(letra);
            actualizarPantalla();

            if (juego.haGanado() || juego.haPerdido()) {
                int respuesta = JOptionPane.showConfirmDialog(GuiAhorcado.this,
                        juego.haGanado() ? "¡Has ganado! ¿Quieres jugar de nuevo?"
                        : "Has perdido. La palabra era: " + juego.getPalabraSecreta() + ". ¿Quieres jugar de nuevo?");
                if (respuesta == JOptionPane.YES_OPTION) {
                    juego.iniciarJuego();
                    actualizarPantalla();
                } else {
                    System.exit(0);
                }
            }
            actualizarPantalla();
        }
    }//GEN-LAST:event_btnInLetraActionPerformed

    /**
     * @param args the command line arguments
     */
    private void actualizarPantalla() {
        labelPalabra.setText("Palabra :   " + new String(juego.getLetrasAcertadas()).replace("", " ").trim());
        label_Intentos.setText("Intentos restantes: " + juego.getIntentosRestantes());
        pistaLabel.setText("Pista : " + juego.getPista());
        textField_LetrasUsadas.setText(juego.getLetrasUsadas().toString());
        ahorcadoDibujo.setErrores(juego.getMaxIntentos() - juego.getIntentosRestantes());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInLetra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPalabra;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel label_Intentos;
    private javax.swing.JLabel label_IntroducirLetra;
    private javax.swing.JPanel panelHorca;
    private javax.swing.JPanel panelLetrasUsadas;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel pistaLabel;
    private javax.swing.JTextField textField_LetraIn;
    private javax.swing.JTextPane textField_LetrasUsadas;
    // End of variables declaration//GEN-END:variables
}
